import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

# Use the full connection string
url = os.getenv("DATABASE_URL")

conn = psycopg2.connect(url)
conn.autocommit = True
cur = conn.cursor()

sql = """
CREATE TABLE IF NOT EXISTS routing_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    preset TEXT NOT NULL,
    route_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
"""

cur.execute(sql)
print("Table routing_history created successfully.")

cur.close()
conn.close()
